name: C/C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile Code
      run: |
        mkdir bin
        gcc -Iinclude src/crypto.c src/main.c -o bin/crypto_engine

    - name: Execute Tests
      run: ./bin/crypto_engine test